DROP TABLE IF EXISTS COMPANY;
DROP TABLE IF EXISTS WASTE;

CREATE TABLE COMPANY (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT UNIQUE NOT NULL,
    PHONE_NUMBER TEXT NOT NULL,
    LOCATION TEXT NOT NULL,
    EMAIL TEXT NOT NULL
);

CREATE TABLE WASTE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    CULTURE TEXT NOT NULL,
    LOCATION TEXT NOT NULL,
    PHONE_NUMBER TEXT NOT NULL,
    AMOUNT TEXT NOT NULL
);
